Repository IndaPlus24/davidn5-mja8-projekt, pull requests merged in 2025-04, with the labels that each got.

#20 Documentation
  README.md
  spec.md
Labels: doc

#21 Feat: controls and inputs
  src/board.rs
  src/main.rs
Labels: feat, func

#25 Feat: Remove line and change from (c,r) to (r,c)
  src/board.rs
  src/main.rs
  src/piece.rs
Labels: feat, func

#27 UI
  res/blue.png
  res/cyan.png
  res/green.png
  res/magenta.png
  res/orange.png
  res/red.png
  res/yellow.png
  src/block.rs
  src/board.rs
  src/main.rs
  src/piece.rs
Labels: feat, gui

#30 Adds 7bag and adds font
  Cargo.lock
  Cargo.toml
  res/tetris_font.ttf
  src/board.rs
  src/main.rs
  src/piece.rs
Labels: fix, feat, func

#33 Feat: basic rotation
  src/board.rs
  src/main.rs
  src/piece.rs
  src/rotation.rs
Labels: feat, func

#41 Fix: fixes rotation
  src/main.rs
Labels: fix

#39 Fix: fixes preload_images
  src/main.rs
Labels: fix

#40 Docs: adds project timeline
  docs/spec.md
  docs/timeline.md
  src/config/controls.rs
  src/config/mod.rs
Labels: doc

#50 Feat: Ghost piece
  res/grey.png
  src/board.rs
  src/main.rs
  src/piece.rs
Labels: feat, gui, func

#53 Fix: fixed mistake from previous pr
  src/piece.rs
Labels: fix

#60 Fixes
  src/block.rs
  src/board.rs
  src/consts.rs
  src/game.rs
  src/game_ui.rs
  src/inputs.rs
  src/main.rs
Labels: feat, func

#61 Feat: Buffer zone
  src/block.rs
  src/board.rs
  src/consts.rs
  src/game.rs
  src/game_ui.rs
  src/inputs.rs
  src/main.rs
  src/piece.rs
  src/rotation.rs
Labels: func

#63 Changes to Movement
  src/consts.rs
  src/game.rs
  src/inputs.rs
  src/main.rs
  src/piece.rs
Labels: fix, feat, func

#68 Start parameters and highscore to file
  Cargo.lock
  Cargo.toml
  README.md
  res/highscore.csv
  src/config/input_config.rs
  src/game.rs
  src/main.rs
Labels: feat, func

#70 GUI: new board textures
  res/blue.png
  res/board/attack_bar.png
  res/board/attack_bar_seperator.png
  res/board/hold.png
  res/board/main_board.png
  res/cyan.png
  res/green.png
  res/grey.png
  res/magenta.png
  res/orange.png
  res/pieces/blue.png
  res/pieces/cyan.png
  res/pieces/gray.png
  res/pieces/green.png
  res/pieces/magenta.png
  res/pieces/orange.png
  res/pieces/red.png
  res/pieces/yellow.png
  res/red.png
  res/tetris_font.ttf
  res/yellow.png
  src/board.rs
  src/consts.rs
  src/game.rs
  src/game_ui.rs
  src/inputs.rs
  src/main.rs
  src/piece.rs
Labels: feat, gui

#73 UI: GUI GOES BRRRRR
  Cargo.lock
  Cargo.toml
  res/PressStart2P-Regular.ttf
  res/ui_assets/empty_box.png
  res/ui_assets/start_screen.png
  src/animation_state.rs
  src/config/input_config.rs
  src/consts.rs
  src/game.rs
  src/inputs.rs
  src/main.rs
  src/ui_components/game_ui.rs
  src/ui_components/gamemode_selector.rs
  src/ui_components/main_menu.rs
  src/ui_components/mod.rs
  src/ui_components/start_screen.rs
Labels: feat, gui

#78 Feat: adds bot selector GUI
  src/animation_state.rs
  src/consts.rs
  src/game.rs
  src/inputs.rs
  src/main.rs
  src/ui_components/bot_selecter.rs
  src/ui_components/mod.rs
Labels: feat, gui

#80 Feat: Scoring system
  res/pieces/red.png
  res/pieces/yellow.png
  src/animation_state.rs
  src/board.rs
  src/config/input_config.rs
  src/consts.rs
  src/game.rs
  src/game_inputs.rs
  src/inputs.rs
  src/main.rs
  src/menu_inputs.rs
  src/rotation.rs
  src/scoring.rs
  src/ui_components/bot_selector.rs
  src/ui_components/game_ui.rs
  src/ui_components/gamemode_selector.rs
  src/ui_components/main_menu.rs
  src/ui_components/mod.rs
  src/ui_components/start_screen.rs
Labels: feat, gui
