Repository IndaPlus24/davidn5-mja8-projekt, pull requests merged in 2025-05, with the labels that each got.

#88 Adds bot
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  src/board.rs
  src/bots/board_evaluation.rs
  src/bots/bot.rs
  src/bots/bot_input.rs
  src/bots/bot_tests.rs
  src/bots/mod.rs
  src/bots/move_outcome.rs
  src/bots/train_bot.rs
  src/consts.rs
  src/game.rs
  src/game_inputs.rs
  src/main.rs
  src/piece.rs
  src/scoring.rs
Labels: feat, func

#93 Feat: Marathon
  src/board.rs
  src/consts.rs
  src/game.rs
  src/game_inputs.rs
  src/gamemodes/marathon.rs
  src/gamemodes/mod.rs
  src/main.rs
  src/menu_inputs.rs
  src/piece.rs
  src/rotation.rs
  src/scoring.rs
  src/ui_components/game_ui.rs
Labels: feat, func

#94 Fixes bots and adds hold functionallity
  README.md
  src/board.rs
  src/bots/board_evaluation.rs
  src/bots/bot.rs
  src/bots/bot_input.rs
  src/bots/bot_tests.rs
  src/bots/move_outcome.rs
  src/bots/train_bot.rs
  src/consts.rs
  src/main.rs
  src/menu_inputs.rs
  src/ui_components/bot_selector.rs
  src/ui_components/gamemode_selector.rs
  src/ui_components/start_screen.rs
Labels: fix, doc, feat, func

#100 UI: Versus basics
  res/misc/line_goal_marker.png
  src/animation_state.rs
  src/board.rs
  src/config/input_config.rs
  src/consts.rs
  src/game.rs
  src/gamemodes/mod.rs
  src/gamemodes/versus.rs
  src/main.rs
  src/menu_inputs.rs
  src/scoring.rs
  src/ui_components/game_ui.rs
  src/ui_components/mod.rs
  src/ui_components/singleplayer_selector.rs
  src/ui_components/versus_ready.rs
Labels: gui

#103 Adds highscores
  res/highscore.csv
  res/highscores/highscore_fourty_lines.csv
  res/highscores/highscore_marathon.csv
  res/highscores/highscore_survival.csv
  src/animation_state.rs
  src/bots/bot_tests.rs
  src/consts.rs
  src/main.rs
  src/menu_inputs.rs
  src/ui_components/high_score.rs
  src/ui_components/main_menu.rs
  src/ui_components/mod.rs
Labels: feat, func

#107 Adds ability to submit highscore
  res/highscores/highscore_fourty_lines.csv
  res/highscores/highscore_marathon.csv
  src/animation_state.rs
  src/game.rs
  src/main.rs
  src/menu_inputs.rs
  src/ui_components/game_ui.rs
  src/ui_components/input_name.rs
  src/ui_components/mod.rs
Labels: feat, func

#108 Feat: garbage
  res/board/attack_bar_seperator.png
  res/board/garbage_b.png
  res/board/garbage_m.png
  res/board/garbage_s.png
  res/board/garbage_t.png
  src/board.rs
  src/consts.rs
  src/game.rs
  src/gamemodes/fourty_lines.rs
  src/gamemodes/marathon.rs
  src/gamemodes/versus/garbage.rs
  src/gamemodes/versus/mod.rs
  src/gamemodes/versus/versus.rs
  src/main.rs
  src/ui_components/game_ui.rs
  src/ui_components/mod.rs
  src/ui_components/stat_formatting.rs
Labels: feat, gui, func

#114 Adds settings, vsbots, countdown, highscore formating and game id
  res/highscores/highscore_fourty_lines.csv
  src/animation_state.rs
  src/bots/bot.rs
  src/bots/bot_tests.rs
  src/consts.rs
  src/game.rs
  src/game_inputs.rs
  src/gamemodes/fourty_lines.rs
  src/gamemodes/survival.rs
  src/main.rs
  src/menu_inputs.rs
  src/piece.rs
  src/ui_components/game_ui.rs
  src/ui_components/high_score.rs
  src/ui_components/mod.rs
  src/ui_components/settings.rs
Labels: feat, gui, func

#119 Fix: versus fixes
  res/board/attack_bar.png
  res/board/hold.png
  res/board/main_board.png
  res/ui_assets/checkbox_c.png
  res/ui_assets/checkbox_e.png
  src/animation_state.rs
  src/bots/bot.rs
  src/consts.rs
  src/game.rs
  src/main.rs
  src/menu_inputs.rs
  src/ui_components/marathon_prompt.rs
  src/ui_components/settings.rs
  src/ui_components/versus_ready.rs
  src/ui_components/versus_rematch.rs
Labels: fix, gui, func

#120 Fix: fixes id generation in reset game and removes button R from 1v1
  src/game.rs
  src/game_inputs.rs
Labels: fix
